from fastapi import APIRouter, Depends, HTTPException, Request
from fastapi.responses import StreamingResponse
from app.dependencies.auth import get_current_user, TokenPayload
from app.schemas.ai import ChatRequest, ChatResponse
from app.services.ai_service import get_ai_service
from slowapi import Limiter
from slowapi.util import get_remote_address
from app.core.config import settings
import logging

logger = logging.getLogger(__name__)
limiter = Limiter(key_func=get_remote_address)

router = APIRouter()


@router.post("/", response_model=ChatResponse)
@limiter.limit(f"{settings.RATE_LIMIT_PER_MINUTE}/minute")
async def chat_endpoint(
    request: Request,
    chat_request: ChatRequest,
    current_user: TokenPayload = Depends(get_current_user)
):
    """
    Endpoint to chat with the Legal AI.
    Requires authentication. Rate limited.
    """
    try:
        ai_service = get_ai_service()
        response_text = await ai_service.chat(chat_request.message, chat_request.history)
        return ChatResponse(response=response_text)
    except Exception as e:
        logger.exception(f"Error in chat endpoint for user {current_user.sub}")
        raise HTTPException(status_code=500, detail="Failed to process chat request")


@router.post("/stream")
@limiter.limit(f"{settings.RATE_LIMIT_PER_MINUTE}/minute")
async def chat_stream_endpoint(
    request: Request,
    chat_request: ChatRequest,
    current_user: TokenPayload = Depends(get_current_user)
):
    """
    Streaming endpoint for real-time chat responses.
    Returns chunks as they are generated by the AI.
    """
    try:
        ai_service = get_ai_service()
        
        async def generate():
            async for chunk in ai_service.chat_stream(chat_request.message, chat_request.history):
                yield f"data: {chunk}\n\n"
            yield "data: [DONE]\n\n"
        
        return StreamingResponse(
            generate(),
            media_type="text/event-stream",
            headers={
                "Cache-Control": "no-cache",
                "Connection": "keep-alive",
            }
        )
    except Exception as e:
        logger.exception(f"Error in streaming chat for user {current_user.sub}")
        raise HTTPException(status_code=500, detail="Failed to process chat request")
