"""Add indexes for optimization

Revision ID: a6b66a5e153a
Revises: 631a19033106
Create Date: 2026-04-16 17:01:59.445354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6b66a5e153a'
down_revision: Union[str, None] = '631a19033106'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_contract_drafts_template_id'), 'contract_drafts', ['template_id'], unique=False)
    op.create_index(op.f('ix_contract_drafts_user_id'), 'contract_drafts', ['user_id'], unique=False)
    op.create_index(op.f('ix_contracts_status'), 'contracts', ['status'], unique=False)
    op.create_index(op.f('ix_contracts_template_id'), 'contracts', ['template_id'], unique=False)
    op.create_index(op.f('ix_contracts_user_id'), 'contracts', ['user_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_contracts_user_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_template_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_status'), table_name='contracts')
    op.drop_index(op.f('ix_contract_drafts_user_id'), table_name='contract_drafts')
    op.drop_index(op.f('ix_contract_drafts_template_id'), table_name='contract_drafts')
    # ### end Alembic commands ###
